# Generated by Django 4.2.6 on 2023-10-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='', verbose_name='profile_pic/'),
        ),
    ]
